# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170419_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.TextField(blank=True, default=''),
        ),
    ]
